# Generated by Django 4.1.5 on 2023-01-28 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='posts/')),
            ],
        ),
    ]
